### ISSUE TITLE
bug/docs: remove reference to `page packs` from CLI docs

### ISSUE THREAD

**Issue by techfg** [skuid/skuid-cli#204]
The [CLI docs](https://docs.skuid.com/latest/en/skuid/cli/#skuid-cli) make reference to `page packs` which appears to only be a supported feature for `Skuid SFX` per the documentation [here](https://docs.skuid.com/latest/en/skuid/pages/page-packs/).

References to `page packs` should be eliminated from `skuid-cli` docs since it only supports `NLX` per the [this comment](https://github.com/skuid/skuid-cli/issues/183#issuecomment-2284814332) in #183.

**Comment by itmightbecody** [comment]
Addressed in the same fix as this thread:
https://github.com/skuid/skuid-cli/issues/183#issuecomment-2307322348
