### ISSUE TITLE
Release 0.3.10 doe not return any metadata with "skuid retrieve"

### ISSUE THREAD

**Issue by matthewleahy** [skuid/skuid-cli#42]
Upgraded skuid CLI to 0.3.10 and the "skuid retrieve" does not return any metadata. Release 0.3.9 is working.

Environment is Windows using PowerShell.

**Comment by plusplusben** [comment]
We found a regression introduced in 0.3.10 that only affects windows. You can follow this PR for the fix. https://github.com/skuid/skuid-cli/pull/45

**Comment by zachelrath** [comment]
@matthewleahy Release 0.3.11 should resolve this issue, can you verify?

**Comment by matthewleahy** [comment]
I can confirm that the issue is resolved and working. Thanks for your help.

  On May 9, 2019 at 10:47 PM Zach McElrath <notifications@github.com> wrote:
 
 
 @matthewleahy Release 0.3.11 should resolve this issue, can you verify?

**Comment by plusplusben** [comment]
Resolve in 0.3.11
