### ISSUE TITLE
README: rename "skuid" directory to "skuid-cli".

### ISSUE THREAD

**Issue by skuid-pkong** [skuid/skuid-cli#43]
Rename to bolded on README & https://docs.skuid.com/latest/en/skuid/cli/
README: wget https://<span></span>github.com/skuid/**skuid-cli**/releases/download/3/skuid_darwin_amd64 -O skuid

Docs: wget $(curl https://<span></span>api.github.com/repos/skuid/**skuid-cli**/releases/latest | grep browser_download_url | grep darwin | awk -F '"' '{print $4}') -O skuid

**Comment by plusplusben** [comment]
Can you submit a PR for this?

**Comment by skuid-pkong** [comment]
Oops, let me do that.

**Comment by plusplusben** [comment]
Fixed with https://github.com/skuid/skuid-cli/pull/44
